# Ejercicios NumPy

Tras hacer tus propias pruebas con la teoría de NumPy, completa los siguientes ejercicios en orden

---
## Ejercicio 1

Antes de empezar a trabajar de verdad, tendrás que importar la librería de NumPy para poder trabajar con ella:

In [32]:
#pip install numpy
import numpy as np

---
## Ejercicio 2

Crea un array de **una dimensión** con los 10 valores que tu quieras y muéstralo por pantalla:

In [33]:
personajes = np.array(
    [
        "Luke Skywalker",
        "Leia Organa",
        "Han Solo",
        "Darth Vader",
        "Yoda",
        "Obi-Wan Kenobi",
        "Chewbacca",
        "R2-D2",
        "C-3PO",
        "Darth Maul",
    ]
)

personajes

array(['Luke Skywalker', 'Leia Organa', 'Han Solo', 'Darth Vader', 'Yoda',
       'Obi-Wan Kenobi', 'Chewbacca', 'R2-D2', 'C-3PO', 'Darth Maul'],
      dtype='<U14')

---
## Ejercicio 3

Crea un array de distinto nombre al anterior de **dos dimensiones** con los 3x3 valores que tu quieras y muéstrala por pantalla:

In [34]:
planetas = np.array(
    [
        ["Tatooine", "Alderaan", "Hoth"],
        ["Endor", "Naboo", "Bespin"],
        ["Coruscant", "Dagobah", "Mustafar"],
    ]
)

planetas

array([['Tatooine', 'Alderaan', 'Hoth'],
       ['Endor', 'Naboo', 'Bespin'],
       ['Coruscant', 'Dagobah', 'Mustafar']], dtype='<U9')

---
## Ejercicio 4

Crea un array de distinto nombre a los anteriores de **tres dimensiones** con los 2x2x2 valores que tu quieras y muéstrala por pantalla:

In [35]:
videojuegos = np.array(
    [
        [
            ["Knights of the Old Republic", "The Force Unleashed"],
            ["Battlefront II (2005)", "Jedi: Fallen Order"],
        ],
        [
            ["Empire at War", "Republic Commando"],
            ["Squadrons", "LEGO Star Wars: The Skywalker Saga"],
        ],
    ]
)

print(videojuegos)

[[['Knights of the Old Republic' 'The Force Unleashed']
  ['Battlefront II (2005)' 'Jedi: Fallen Order']]

 [['Empire at War' 'Republic Commando']
  ['Squadrons' 'LEGO Star Wars: The Skywalker Saga']]]


---
## Ejercicio 5

Muestra las dimensiones, el tamaño y la forma que tienen las tres matrices creadas anteriormente:

In [36]:
info_personajes = (personajes.ndim, personajes.size, personajes.shape)
info_planetas = (planetas.ndim, planetas.size, planetas.shape)
info_videojuegos = (videojuegos.ndim, videojuegos.size, videojuegos.shape)

print(f"Personajes: {info_personajes},\nPlanetas: {info_planetas},\nVideojuegos: {info_videojuegos}")

Personajes: (1, 10, (10,)),
Planetas: (2, 9, (3, 3)),
Videojuegos: (3, 8, (2, 2, 2))


---
## Ejercicio 6

Crea un array con todos los múltiplos de 5 en una sola instrucción y muéstralo por pantalla:

In [37]:
multiplos_de_5 = np.arange(0, 101, 5)

multiplos_de_5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

---
## Ejercicio 7

Crea un array con 20 valores entre los números 1 y 2. Estos valores deben estar distribuídos de manera equitativa:

In [38]:
valores_equitativos = np.linspace(1, 2, 20)

valores_equitativos

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

---
## Ejercicio 8

Crea una matriz de forma 2x3 y muéstrala por pantalla. A continuación cambia su forma a una matriz 3x2

In [39]:
matriz_2x3 = np.array([[1, 2, 3], [4, 5, 6]])

print("Matriz original 2x3:")
print(matriz_2x3)

matriz_3x2 = matriz_2x3.reshape(3, 2)

print("\nMatriz reconfigurada a 3x2:")
matriz_3x2

Matriz original 2x3:
[[1 2 3]
 [4 5 6]]

Matriz reconfigurada a 3x2:


array([[1, 2],
       [3, 4],
       [5, 6]])

---
## Ejercicio 9

Crea una matriz de 3x6 con valores aleatorios. Después muestra por pantalla las siguientes convinaciones:
*   La primera fila entera
*   La primera columna entera
*   Todos los valores entre las columnas 2 y 4
*   Todos los valores de las filas 1 y 2
*   Todos los valores entre las filas 2 y 3 y las columnas 5 y 6

In [40]:
# Creando una matriz de 3x6 con valores aleatorios
matriz_aleatoria_3x6 = np.random.rand(3, 6)

# Mostrando la matriz creada
print("Matriz aleatoria 3x6:")
print(matriz_aleatoria_3x6)

# Extrayendo la primera fila entera
primera_fila = matriz_aleatoria_3x6[0, :]

# Extrayendo la primera columna entera
primera_columna = matriz_aleatoria_3x6[:, 0]

# Extrayendo todos los valores entre las columnas 2 y 4 (recordando que Python indexa desde 0)
columnas_2_a_4 = matriz_aleatoria_3x6[:, 1:4]

# Extrayendo todos los valores de las filas 1 y 2
filas_1_y_2 = matriz_aleatoria_3x6[0:2, :]

# Extrayendo todos los valores entre las filas 2 y 3 y las columnas 5 y 6
filas_2_y_3_columnas_5_y_6 = matriz_aleatoria_3x6[1:3, 4:6]


print(f"Primera fila: {primera_fila},\nPrimera columna: {primera_columna},\nColumnas de la 2 a la 4: {columnas_2_a_4},\Filas 1 y 2: {filas_1_y_2},\nFilas 2 y 3 & Columnas 5 y 6: {filas_2_y_3_columnas_5_y_6}")

Matriz aleatoria 3x6:
[[0.36696904 0.99634366 0.55390584 0.78327295 0.84562221 0.60527516]
 [0.16426288 0.51120178 0.22338575 0.49773133 0.97260821 0.28904266]
 [0.64308977 0.54975611 0.23284232 0.40965009 0.50479102 0.45819672]]
Primera fila: [0.36696904 0.99634366 0.55390584 0.78327295 0.84562221 0.60527516],
Primera columna: [0.36696904 0.16426288 0.64308977],
Columnas de la 2 a la 4: [[0.99634366 0.55390584 0.78327295]
 [0.51120178 0.22338575 0.49773133]
 [0.54975611 0.23284232 0.40965009]],\Filas 1 y 2: [[0.36696904 0.99634366 0.55390584 0.78327295 0.84562221 0.60527516]
 [0.16426288 0.51120178 0.22338575 0.49773133 0.97260821 0.28904266]],
Filas 2 y 3 & Columnas 5 y 6: [[0.97260821 0.28904266]
 [0.50479102 0.45819672]]


---
## Ejercicio 10

Crea un array de tamaño 1x5. Después añádele 5 elementos nuevos. Por último, elimina los dos primeros valores y muéstralo por pantalla:

In [41]:
inicial = np.array([1, 2, 3, 4, 5])

elementos_nuevos = np.array([6, 7, 8, 9, 10])
ampliado = np.concatenate((inicial, elementos_nuevos))

final = np.delete(ampliado, [0, 1])

final

array([ 3,  4,  5,  6,  7,  8,  9, 10])

---
## Ejercicio 11

Crea dos matrices 3x3, una con valores aleatorios y otra de identidad. Realiza las cuatro operaciones básicas entre ellas (suma, resta, multiplicación y división). Por último, calcula la raíz cuadrada de matriz de identidad.

In [42]:
aleatoria = np.random.rand(3, 3)

mIdentidad = np.eye(3)

suma = aleatoria + mIdentidad
resta = aleatoria - mIdentidad
multiplicacion = np.dot(aleatoria, mIdentidad)
division = aleatoria / mIdentidad


r2identidad = np.sqrt(mIdentidad)

print(f"Suma: {suma},\nResta: {resta},\nMultiplicación: {multiplicacion},\nDivisión: {division},\nRaíz Cuadrada: {r2identidad}")

Suma: [[1.2520493  0.40681402 0.06633074]
 [0.09083494 1.47772988 0.90323262]
 [0.66067811 0.9197238  1.33500457]],
Resta: [[-0.7479507   0.40681402  0.06633074]
 [ 0.09083494 -0.52227012  0.90323262]
 [ 0.66067811  0.9197238  -0.66499543]],
Multiplicación: [[0.2520493  0.40681402 0.06633074]
 [0.09083494 0.47772988 0.90323262]
 [0.66067811 0.9197238  0.33500457]],
División: [[0.2520493         inf        inf]
 [       inf 0.47772988        inf]
 [       inf        inf 0.33500457]],
Raíz Cuadrada: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


C:\Users\Noelia\AppData\Local\Temp\ipykernel_18468\2477938965.py:8: RuntimeWarning: divide by zero encountered in divide
  division = aleatoria / mIdentidad


---
## Ejercicio 12

Sin utilizar las funciones std, mean y median de NumPy, programa dichas funcionalidades:

In [45]:
def calcular_media(array):
    return sum(array) / len(array)

def calcular_mediana(array):
    array_ordenado = sorted(array)
    n = len(array_ordenado)
    mitad = n // 2
    if n % 2 == 0:
        return (array_ordenado[mitad - 1] + array_ordenado[mitad]) / 2
    else:
        return array_ordenado[mitad]

def calcular_desviacion_estandar(array):
    media = calcular_media(array)
    varianza = sum((x - media) ** 2 for x in array) / len(array)
    return varianza ** 0.5

array_ejemplo = np.array([1, 2, 3, 4, 5])

media = calcular_media(array_ejemplo)
mediana = calcular_mediana(array_ejemplo)
desviacion_estandar = calcular_desviacion_estandar(array_ejemplo)

media, mediana, desviacion_estandar
print(f"Media: {media},\nMediana: {mediana},\nDesviación estándar: {desviacion_estandar}")

Media: 3.0,
Mediana: 3,
Desviación estándar: 1.4142135623730951
